logging:
  level: INFO # logging level, e.g., INFO
  logpath: /data/zenghaoqiu/repo/OpenScope/ChatDev/puppeteer/logs # the path to the folder for storing log files
model_weight_path: /data/zenghaoqiu/models/Skywork-Reward-Llama-3.1-8B # the path to the folder containing model weights of the puppeteer model base
api_keys:
  openai_api_key: sk-a5defe25688f4fcc9c20aae1ac3010f0 # openai api key
  openai_base_url: https://dashscope.aliyuncs.com/compatible-mode/v1 # openai base url, e.g., https://api.openai.com/v1/
  bing_api_key: 5708e7478894c1d65f7aa497384662aeb00b6b8d6843fa863d14a4fa7f6285fe # bing api key for web search

max_retry_times: 10 # maximum number of times to retry API calls
max_json_reformat_turns: 10 # maximum number of times to retry JSON parsing/reformatting
external_tools_enabled: True # whether to enable external tools like web search, file search, etc.

file_path:
  root_file_path: /data/zenghaoqiu/repo/OpenScope/ChatDev/puppeteer # the path to the folder containing all the files which agents might need

graph:
  max_parallel_paths: 4 # maximum number of parallel paths to explore in the graph
  max_step_num: 5 # maximum number of steps (nodes) in each path